# pgmp -- Travis CI configuration
#
# Copyright (C) 2020 Daniele Varrazzo
#
# This file is part of the PostgreSQL GMP Module

language: python

matrix:
  include:
    - addons:
        postgresql: '9.4'
        apt:
          packages:
            - postgresql-client-9.4
            - postgresql-server-dev-9.4
    - addons:
        postgresql: '9.5'
        apt:
          packages:
            - postgresql-client-9.5
            - postgresql-server-dev-9.5
    - addons:
        postgresql: '9.6'
        apt:
          packages:
            - postgresql-client-9.6
            - postgresql-server-dev-9.6
    - addons:
        postgresql: '10'
        apt:
          packages:
            - postgresql-client-10
            - postgresql-server-dev-10
    - addons:
        postgresql: '11'
        apt:
          packages:
            - postgresql-11
            - postgresql-client-11
            - postgresql-server-dev-11
      env:
        PGPORT: "5433"
    - addons:
        postgresql: '12'
        apt:
          packages:
            - postgresql-12
            - postgresql-client-12
            - postgresql-server-dev-12
      env:
        PGPORT: "5433"

install:
  - make
  - sudo make install

script:
  - make installcheck

notifications:
  email: false
